version: '3.5'

services: 
  app:
    build: 
      context: .
      target: build
    volumes: 
      - ./:/go/app
    command: realize start --run --no-config
    ports: 
      - 8080:8080
    depends_on: 
      - db
  db:
    image: postgres:latest
    container_name: go_db
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment: 
      POSTGRES_DB: blog
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: docker_user_pwd
volumes: 
  postgres_data: