version: '3.5'

services: 
  app:
    build: 
      context: .
      target: build
    volumes: 
      - ./:/go/app
    command: realize start --run --no-config
    ports: 
      - 8080:8080
    depends_on: 
      - db
  db:
    image: mysql:latest
    container_name: go_db
    volumes: 
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: docker_pwd
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_user_pwd
volumes: 
  mysql_data: